# .github/workflows/test.yml
name: Basic Test Workflow

on:
  push:
    branches: [ main ]  # 或者你的主分支名

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Print working directory
        run: |
          pwd
          ls -la
          
      - name: Download CLI tool
        run: |
          # 创建bin目录
          mkdir -p $GITHUB_WORKSPACE/bin
          cd $GITHUB_WORKSPACE/bin
          
          # 下载CLI工具
          wget https://github.com/langgenius/dify-plugin-daemon/releases/download/0.0.6/dify-plugin-linux-amd64
          chmod +x dify-plugin-linux-amd64
          
          # 显示下载位置和文件
          echo "CLI tool location:"
          pwd
          ls -la dify-plugin-linux-amd64
          
      - name: Get Version from manifest
        id: get_version
        run: |
          VERSION=$(grep "^version:" manifest.yaml | cut -d' ' -f2)
          echo "Plugin version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Package Plugin
        run: |
          # 使用下载的CLI工具进行打包
          cd $GITHUB_WORKSPACE
          PACKAGE_NAME="exa-${VERSION}.difypkg"
          ./bin/dify-plugin-linux-amd64 plugin package . -o "$PACKAGE_NAME"
          
          # 显示打包结果
          echo "Package result:"
          ls -la "$PACKAGE_NAME"
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          
      - name: Print environment info
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Current directory contents:"
          ls -R
