# .github/workflows/test.yml
name: Basic Test Workflow

on:
  push:
    branches: [ main ]  # 或者你的主分支名

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Print working directory
        run: |
          pwd
          ls -la
          
      - name: Download CLI tool
        run: |
          # 创建bin目录
          mkdir -p $GITHUB_WORKSPACE/bin
          cd $GITHUB_WORKSPACE/bin
          
          # 下载CLI工具
          wget https://github.com/langgenius/dify-plugin-daemon/releases/download/0.0.6/dify-plugin-linux-amd64
          chmod +x dify-plugin-linux-amd64
          
          # 显示下载位置和文件
          echo "CLI tool location:"
          pwd
          ls -la dify-plugin-linux-amd64
          
      - name: Get Version from manifest
        id: get_version
        run: |
          VERSION=$(grep "^version:" manifest.yaml | cut -d' ' -f2)
          echo "Plugin version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
      - name: Package Plugin
        id: package
        run: |
          # 使用下载的CLI工具进行打包
          cd $GITHUB_WORKSPACE
          PACKAGE_NAME="exa-${{ steps.get_version.outputs.version }}.difypkg"
          ./bin/dify-plugin-linux-amd64 plugin package . -o "$PACKAGE_NAME"
          
          # 显示打包结果
          echo "Package result:"
          ls -la "$PACKAGE_NAME"
          echo "package_name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          
          # 显示完整的文件路径和目录结构
          echo "\nFull file path:"
          pwd
          echo "\nDirectory structure:"
          tree || ls -R

      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: Yevanchen/dify-plugins
          path: dify-plugins
          token: ${{ secrets.PLUGIN_ACTION }}
          fetch-depth: 0
          
      - name: Prepare and create PR
        run: |
          # Debug info
          echo "Debug: Current directory $(pwd)"
          echo "Debug: Looking for package in: $GITHUB_WORKSPACE"
          ls -la $GITHUB_WORKSPACE
          
          # 移动打包文件到目标目录
          PACKAGE_NAME="exa-${{ steps.get_version.outputs.version }}.difypkg"
          mkdir -p $GITHUB_WORKSPACE/dify-plugins/yevanchen/exa
          mv $GITHUB_WORKSPACE/$PACKAGE_NAME $GITHUB_WORKSPACE/dify-plugins/yevanchen/exa/
          
          # 进入目标仓库目录
          cd $GITHUB_WORKSPACE/dify-plugins
          
          # 配置git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # 确保远程配置正确
          git remote -v
          git remote set-url origin https://x-access-token:${{ secrets.PLUGIN_ACTION }}@github.com/Yevanchen/dify-plugins.git
          
          # 创建并切换到新分支
          BRANCH_NAME="update-exa-plugin-${{ steps.get_version.outputs.version }}"
          git checkout -b "$BRANCH_NAME"
          
          # 添加并提交更改
          git add yevanchen/exa/
          git status # debug用
          git commit -m "Update exa plugin to version ${{ steps.get_version.outputs.version }}"
          
          # 推送到远程
          git push origin "$BRANCH_NAME"
          
          # 确认分支已经推送
          git branch -a
          
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "update-exa-plugin-${{ steps.get_version.outputs.version }}"
          destination_repository: "langgenius/dify-plugins"
          destination_branch: "main"
          pr_title: "Update exa plugin to version ${{ steps.get_version.outputs.version }}"
          pr_body: |
            Update exa plugin package to version ${{ steps.get_version.outputs.version }}
            
            Changes:
            - Updated plugin package file
          github_token: ${{ secrets.PLUGIN_ACTION }}
          pr_allow_empty: true

      - name: Print environment info
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Current directory contents:"
          ls -R
